// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartSunnyCore(arg1) {
  return window['go']['main']['App']['StartSunnyCore'](arg1);
}

export function StopSunnyCore() {
  return window['go']['main']['App']['StopSunnyCore']();
}
