// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppendToRequestLog(arg1:string):Promise<main.Result>;

export function GetJSFiles():Promise<Array<main.FileInfo>>;

export function LoadSessionFromFile():Promise<main.Result>;

export function ReadFileToBase64(arg1:string):Promise<string>;

export function RemoveLogFile():Promise<main.Result>;

export function RemoveSessionFile():Promise<main.Result>;

export function SaveSessionToFile(arg1:string):Promise<main.Result>;

export function StartSunnyCore(arg1:number):Promise<main.Result>;

export function StopSunnyCore():Promise<main.Result>;
