// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function StartSunnyCore(arg1:number):Promise<main.Result>;

export function StopSunnyCore():Promise<main.Result>;
