// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendToRequestLog(arg1) {
  return window['go']['main']['App']['AppendToRequestLog'](arg1);
}

export function GetJSFiles() {
  return window['go']['main']['App']['GetJSFiles']();
}

export function LoadSessionFromFile() {
  return window['go']['main']['App']['LoadSessionFromFile']();
}

export function ReadFileToBase64(arg1) {
  return window['go']['main']['App']['ReadFileToBase64'](arg1);
}

export function RemoveLogFile() {
  return window['go']['main']['App']['RemoveLogFile']();
}

export function RemoveSessionFile() {
  return window['go']['main']['App']['RemoveSessionFile']();
}

export function SaveSessionToFile(arg1) {
  return window['go']['main']['App']['SaveSessionToFile'](arg1);
}

export function StartSunnyCore(arg1) {
  return window['go']['main']['App']['StartSunnyCore'](arg1);
}

export function StopSunnyCore() {
  return window['go']['main']['App']['StopSunnyCore']();
}
